# Generated by Django 5.2.7 on 2025-10-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('temps_preparation', models.IntegerField(default=0)),
                ('temps_cuisson', models.IntegerField(default=0)),
                ('ingredients', models.JSONField(default=list)),
                ('etapes', models.TextField(blank=True)),
                ('tags', models.JSONField(default=list)),
            ],
        ),
    ]
