# Generated by Django 5.2.7 on 2025-10-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='recette',
            name='ingredients',
            field=models.TextField(blank=True, help_text='Mettez un ingrédient par ligne (ex: 2 courgettes)'),
        ),
        migrations.RemoveField(
            model_name='recette',
            name='tags',
        ),
        migrations.AddField(
            model_name='recette',
            name='tags',
            field=models.ManyToManyField(blank=True, to='recettes.tag'),
        ),
    ]
