# Generated by Django 5.2.7 on 2025-10-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0002_tag_alter_recette_ingredients_remove_recette_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='lien_source',
            field=models.URLField(blank=True, help_text='Lien vers la recette (Instagram, blog...)', max_length=500, null=True),
        ),
    ]
