# Generated by Django 5.1.1 on 2025-02-11 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_tag_recipe_tags'),
        ('planner', '0002_remove_mealplan_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Date du lundi de la semaine concernée', unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='user',
        ),
        migrations.CreateModel(
            name='DayPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date de ce jour')),
                ('dinner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dinner_plans', to='main.recipe')),
                ('lunch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lunch_plans', to='main.recipe')),
                ('week_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_plans', to='planner.weekplan')),
            ],
        ),
        migrations.DeleteModel(
            name='Planning',
        ),
        migrations.DeleteModel(
            name='UserPreference',
        ),
    ]
