# Generated by Django 5.1.1 on 2025-01-22 09:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ingredients/')),
                ('season', models.CharField(blank=True, choices=[('Hiver', 'Hiver'), ('Printemps', 'Printemps'), ('Été', 'Été'), ('Automne', 'Automne')], max_length=20, null=True)),
                ('is_halal', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Hiver', 'Hiver'), ('Printemps', 'Printemps'), ('Été', 'Été'), ('Automne', 'Automne')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique pour lier la recette à une BDD générale', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('cooking_time', models.PositiveIntegerField(help_text='Temps de cuisson en minutes')),
                ('is_veggie', models.BooleanField(default=False)),
                ('servings', models.PositiveIntegerField()),
                ('is_easy', models.BooleanField(default=False)),
                ('steps', models.TextField()),
                ('utensils', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Note entre 1 et 5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_private', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(help_text="L'utilisateur qui a créé cette recette", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to=settings.AUTH_USER_MODEL)),
                ('ingredients', models.ManyToManyField(related_name='recipes', to='main.ingredient')),
                ('seasons', models.ManyToManyField(blank=True, help_text='Saisons associées à la recette', related_name='recipes', to='main.season')),
            ],
        ),
    ]
