# Generated by Django 5.1.1 on 2025-01-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_recipe_image_remove_recipe_steps_step_recipe_steps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='steps',
        ),
        migrations.DeleteModel(
            name='Step',
        ),
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=models.TextField(default='False'),
        ),
    ]
