# Generated by Django 5.1.1 on 2025-01-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_recipe_difficulty_recipe_preparation_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(blank=True, choices=[('Entrée', 'Entrée'), ('Plat Principal', 'Plat Principal'), ('Dessert', 'Dessert')], max_length=20, null=True),
        ),
    ]
