# Generated by Django 5.1.1 on 2025-02-11 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_tag_recipe_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='is_easy',
        ),
    ]
